# Variables
shift_escape = Shift{!150ms}

# Default Keys
CapsLock{80ms} >> ControlLeft

# Key Maps
[title="/NVIM|Code|Obsidian/i"]
shift_escape >> Escape

[class="/zed/i"]
shift_escape >> Escape

[title="/Firefox|zen/i"]
shift_escape           >> ControlLeft{C}
(ControlLeft Shift){Z} >> "${"

[title="/Blender/i"]
Shift >> Shift
