
background {{colors.surface.default.hex}}
foreground {{colors.on_surface.default.hex}}
selection_background {{colors.on_secondary.default.hex}}
selection_foreground {{colors.secondary_fixed_dim.default.hex}}
url_color {{colors.primary.default.hex}}
cursor {{colors.on_surface.default.hex}}
cursor_text_color {{colors.background.default.hex}}

# Tabs
active_tab_background {{colors.primary.default.hex}}
active_tab_foreground {{colors.surface.default.hex}}
inactive_tab_background {{colors.surface.default.hex}}
inactive_tab_foreground {{colors.on_surface.default.hex | set_lightness: -50.0}}

# Windows
active_border_color {{colors.primary.default.hex}}
inactive_border_color {{colors.primary.default.hex | set_lightness: -20.0}}
